import { PrismaService } from '../prisma/prisma.service';
import { UserRole } from '@prisma/client';
export declare class UsersService {
    private prisma;
    constructor(prisma: PrismaService);
    findByRole(role: UserRole, tenantId?: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    }[]>;
    findAllByTenant(tenantId: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    }[]>;
    findAdmin(tenantId: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    } | null>;
}
