import { UsersService } from './users.service';
export declare class UsersController {
    private readonly usersService;
    constructor(usersService: UsersService);
    findTechnicians(tenantId?: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    }[]>;
    findOwners(tenantId?: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    }[]>;
    findAdmin(tenantId: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    } | null>;
    findAll(tenantId: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    }[]>;
}
