import { PrismaService } from '../prisma/prisma.service';
import { ProviderSpecialty } from '@prisma/client';
export declare class ProvidersService {
    private prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string): Promise<({
        additionalContacts: {
            id: string;
            createdAt: Date;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            phone: string | null;
            photoUrl: string | null;
            providerId: string;
        }[];
        technicians: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            photoUrl: string | null;
        }[];
    } & {
        id: string;
        name: string;
        nit: string | null;
        status: import("@prisma/client").$Enums.ProviderStatus;
        createdAt: Date;
        email: string | null;
        phone: string | null;
        photoUrl: string | null;
        tenantId: string;
        address: string | null;
        specialty: import("@prisma/client").$Enums.ProviderSpecialty;
        rating: number | null;
        contactName: string | null;
        contactLastName: string | null;
        contactId: string | null;
        contactPhone: string | null;
        legalArl: string | null;
        legalSst: boolean;
        legalPolicyNumber: string | null;
        updatedAt: Date;
    })[]>;
    findOne(id: string): Promise<({
        additionalContacts: {
            id: string;
            createdAt: Date;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            phone: string | null;
            photoUrl: string | null;
            providerId: string;
        }[];
        technicians: {
            id: string;
            createdAt: Date;
            email: string;
            passwordHash: string;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            role: import("@prisma/client").$Enums.UserRole;
            phone: string | null;
            whatsappId: string | null;
            photoUrl: string | null;
            isActive: boolean;
            additionalContacts: string | null;
            personType: string | null;
            isTaxDeclarant: boolean;
            regimeType: string | null;
            applyReteIva: boolean;
            applyReteFuente: boolean;
            applyReteIca: boolean;
            bankName: string | null;
            accountNumber: string | null;
            accountType: string | null;
            tenantId: string | null;
            roleId: string | null;
            providerId: string | null;
        }[];
    } & {
        id: string;
        name: string;
        nit: string | null;
        status: import("@prisma/client").$Enums.ProviderStatus;
        createdAt: Date;
        email: string | null;
        phone: string | null;
        photoUrl: string | null;
        tenantId: string;
        address: string | null;
        specialty: import("@prisma/client").$Enums.ProviderSpecialty;
        rating: number | null;
        contactName: string | null;
        contactLastName: string | null;
        contactId: string | null;
        contactPhone: string | null;
        legalArl: string | null;
        legalSst: boolean;
        legalPolicyNumber: string | null;
        updatedAt: Date;
    }) | null>;
    create(tenantId: string, data: {
        name: string;
        nit?: string;
        email?: string;
        phone?: string;
        address?: string;
        specialty: ProviderSpecialty;
        contactName?: string;
        contactLastName?: string;
        contactId?: string;
        contactPhone?: string;
        photoUrl?: string;
        legalArl?: string;
        legalSst?: boolean;
        legalPolicyNumber?: string;
        additionalContacts?: any[];
    }): Promise<{
        additionalContacts: {
            id: string;
            createdAt: Date;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            phone: string | null;
            photoUrl: string | null;
            providerId: string;
        }[];
    } & {
        id: string;
        name: string;
        nit: string | null;
        status: import("@prisma/client").$Enums.ProviderStatus;
        createdAt: Date;
        email: string | null;
        phone: string | null;
        photoUrl: string | null;
        tenantId: string;
        address: string | null;
        specialty: import("@prisma/client").$Enums.ProviderSpecialty;
        rating: number | null;
        contactName: string | null;
        contactLastName: string | null;
        contactId: string | null;
        contactPhone: string | null;
        legalArl: string | null;
        legalSst: boolean;
        legalPolicyNumber: string | null;
        updatedAt: Date;
    }>;
    update(id: string, data: any): Promise<{
        id: string;
        name: string;
        nit: string | null;
        status: import("@prisma/client").$Enums.ProviderStatus;
        createdAt: Date;
        email: string | null;
        phone: string | null;
        photoUrl: string | null;
        tenantId: string;
        address: string | null;
        specialty: import("@prisma/client").$Enums.ProviderSpecialty;
        rating: number | null;
        contactName: string | null;
        contactLastName: string | null;
        contactId: string | null;
        contactPhone: string | null;
        legalArl: string | null;
        legalSst: boolean;
        legalPolicyNumber: string | null;
        updatedAt: Date;
    }>;
    remove(id: string): Promise<{
        id: string;
        name: string;
        nit: string | null;
        status: import("@prisma/client").$Enums.ProviderStatus;
        createdAt: Date;
        email: string | null;
        phone: string | null;
        photoUrl: string | null;
        tenantId: string;
        address: string | null;
        specialty: import("@prisma/client").$Enums.ProviderSpecialty;
        rating: number | null;
        contactName: string | null;
        contactLastName: string | null;
        contactId: string | null;
        contactPhone: string | null;
        legalArl: string | null;
        legalSst: boolean;
        legalPolicyNumber: string | null;
        updatedAt: Date;
    }>;
    assignTechnician(providerId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        email: string;
        passwordHash: string;
        firstName: string;
        lastName: string;
        governmentId: string | null;
        role: import("@prisma/client").$Enums.UserRole;
        phone: string | null;
        whatsappId: string | null;
        photoUrl: string | null;
        isActive: boolean;
        additionalContacts: string | null;
        personType: string | null;
        isTaxDeclarant: boolean;
        regimeType: string | null;
        applyReteIva: boolean;
        applyReteFuente: boolean;
        applyReteIca: boolean;
        bankName: string | null;
        accountNumber: string | null;
        accountType: string | null;
        tenantId: string | null;
        roleId: string | null;
        providerId: string | null;
    }>;
}
