import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class PropertiesService {
  constructor(private prisma: PrismaService) {}

  async create(data: any) {
    // Geocoding Simulation: Resolving coordinates based on address
    let latitude = data.latitude;
    let longitude = data.longitude;

    if (!latitude || !longitude) {
      // Logic would call Google Geocoding API here
      // For simulation, we generate consistent random-ish coords for the address string
      const seed = data.address.length;
      latitude = 4.6097 + (seed % 100) / 1000;
      longitude = -74.0817 + (seed % 100) / 1000;
    }

    const { ownerInfo, tenantInfo, attachments, ...propertyFields } = data;

    const property = await this.prisma.property.create({
      data: {
        tenantId: propertyFields.tenantId,
        title: propertyFields.title,
        propertyType: propertyFields.propertyType,
        address: propertyFields.address,
        city: propertyFields.city,
        department: propertyFields.department,
        country: propertyFields.country,
        areaM2: propertyFields.areaM2,
        rooms: propertyFields.rooms,
        bathrooms: propertyFields.bathrooms,
        status: propertyFields.status,
        propertyCode: propertyFields.propertyCode,
        isVip: propertyFields.isVip || false,
        inventoryTemplateId: propertyFields.inventoryTemplateId,
        rentAmount: propertyFields.rentAmount,
        adminAmount: propertyFields.adminAmount,
        taxAmount: propertyFields.taxAmount,
        managementName: propertyFields.managementName,
        managementNit: propertyFields.managementNit,
        insuranceCompany: propertyFields.insuranceCompany,
        splatUrl: propertyFields.splatUrl,
        attachments: attachments || [],
        latitude,
        longitude
      }
    });

    // 1. Handle Owner Persistence
    if (ownerInfo && ownerInfo.name) {
      // Find or create owner user
      let ownerUser = await this.prisma.user.findFirst({
        where: { 
          OR: [
            { email: ownerInfo.email || 'pending_email' },
            { phone: ownerInfo.phone }
          ]
        }
      });

      if (!ownerUser) {
        ownerUser = await this.prisma.user.create({
          data: {
            tenantId: propertyFields.tenantId,
            email: ownerInfo.email || `owner_${Date.now()}@teus.com`,
            passwordHash: 'vault_autogenerated',
            firstName: ownerInfo.name,
            lastName: ownerInfo.lastName || 'Propietario',
            role: 'OWNER',
            phone: ownerInfo.phone,
            personType: ownerInfo.personType,
            isTaxDeclarant: ownerInfo.isTaxDeclarant || false,
            regimeType: ownerInfo.regimeType,
            applyReteIva: ownerInfo.applyReteIva || false,
            applyReteFuente: ownerInfo.applyReteFuente || false,
            applyReteIca: ownerInfo.applyReteIca || false,
            bankName: ownerInfo.bankName,
            accountNumber: ownerInfo.accountNumber
          }
        });
      }

      await this.prisma.propertyRelation.create({
        data: {
          propertyId: property.id,
          userId: ownerUser.id,
          relationType: 'OWNER',
          startDate: new Date(),
          status: 'ACTIVE'
        }
      });
    }

    // 2. Handle Tenant Persistence (if RENTED)
    if (tenantInfo && tenantInfo.firstName) {
      let tenantUser = await this.prisma.user.findFirst({
        where: {
          OR: [
            { email: tenantInfo.email || 'pending_email' },
            { governmentId: tenantInfo.governmentId }
          ]
        }
      });

      if (!tenantUser) {
        tenantUser = await this.prisma.user.create({
          data: {
            tenantId: propertyFields.tenantId,
            email: tenantInfo.email || `tenant_${Date.now()}@teus.com`,
            passwordHash: 'vault_autogenerated',
            firstName: tenantInfo.firstName,
            lastName: tenantInfo.lastName,
            role: 'TENANT_USER',
            phone: tenantInfo.phone,
            governmentId: tenantInfo.governmentId,
            personType: tenantInfo.personType || 'NATURAL'
          }
        });
      }

      await this.prisma.propertyRelation.create({
        data: {
          propertyId: property.id,
          userId: tenantUser.id,
          relationType: 'TENANT',
          startDate: tenantInfo.contractStart ? new Date(tenantInfo.contractStart) : new Date(),
          endDate: tenantInfo.contractEnd ? new Date(tenantInfo.contractEnd) : null,
          contractNumber: tenantInfo.contractNumber,
          contractType: tenantInfo.contractType,
          insuranceCompany: tenantInfo.insuranceCompany,
          status: 'ACTIVE'
        }
      });
    }

    // If an inventory template was selected, apply it
    if (data.inventoryTemplateId) {
      const template = await this.prisma.inventoryTemplate.findUnique({
        where: { id: data.inventoryTemplateId },
        include: { items: true }
      });

      if (template) {
        const inventoryItems = template.items.map((item: any) => ({
          propertyId: property.id,
          name: item.name,
          category: item.category,
          condition: 'GOOD' as any,
          description: `Generado desde plantilla: ${item.material || ''} ${item.description || ''}`
        }));

        await this.prisma.inventoryItem.createMany({
          data: inventoryItems
        });
      }
    }

    return property;
  }

  async findAllByTenant(tenantId: string) {
    return this.prisma.property.findMany({
      where: { tenantId },
      include: {
        assignments: {
          include: { agent: true }
        },
        relations: {
          include: { user: true }
        },
        inventoryItems: true
      },
      orderBy: { createdAt: 'desc' }
    });
  }

  async updateStatus(id: string, isActive: boolean) {
    return this.prisma.property.update({
      where: { id },
      data: { isActive }
    });
  }

  async findByPropertyCode(tenantId: string, propertyCode: string) {
    return this.prisma.property.findFirst({
      where: { tenantId, propertyCode },
      include: {
        relations: {
          include: { user: true }
        }
      }
    });
  }

  async findOne(id: string) {
    return this.prisma.property.findUnique({
      where: { id },
      include: {
        relations: {
          include: { user: true }
        }
      }
    });
  }

  async update(id: string, data: any) {
    const { ownerInfo, tenantInfo, attachments, ...propertyFields } = data;
    
    // Update basic fields
    const property = await this.prisma.property.update({
      where: { id },
      data: {
        title: propertyFields.title,
        propertyType: propertyFields.propertyType,
        address: propertyFields.address,
        city: propertyFields.city,
        department: propertyFields.department,
        country: propertyFields.country,
        areaM2: propertyFields.areaM2,
        rooms: propertyFields.rooms,
        bathrooms: propertyFields.bathrooms,
        status: propertyFields.status,
        propertyCode: propertyFields.propertyCode,
        isVip: propertyFields.isVip,
        rentAmount: propertyFields.rentAmount,
        adminAmount: propertyFields.adminAmount,
        taxAmount: propertyFields.taxAmount,
        managementName: propertyFields.managementName,
        managementNit: propertyFields.managementNit,
        insuranceCompany: propertyFields.insuranceCompany,
        splatUrl: propertyFields.splatUrl,
        attachments: attachments || [],
        latitude: propertyFields.latitude,
        longitude: propertyFields.longitude
      }
    });

    // Update or Create Owner Relation
    if (ownerInfo && ownerInfo.name) {
      let ownerUser = await this.prisma.user.findFirst({
        where: { OR: [{ email: ownerInfo.email || 'pending' }, { phone: ownerInfo.phone }] }
      });

      if (!ownerUser) {
        ownerUser = await this.prisma.user.create({
          data: {
            tenantId: property.tenantId,
            email: ownerInfo.email || `owner_${Date.now()}@teus.com`,
            passwordHash: 'vault_autogenerated',
            firstName: ownerInfo.name,
            lastName: ownerInfo.lastName || 'Propietario',
            role: 'OWNER',
            phone: ownerInfo.phone,
            personType: ownerInfo.personType,
            isTaxDeclarant: ownerInfo.isTaxDeclarant,
            regimeType: ownerInfo.regimeType,
            applyReteIva: ownerInfo.applyReteIva,
            applyReteFuente: ownerInfo.applyReteFuente,
            applyReteIca: ownerInfo.applyReteIca,
            bankName: ownerInfo.bankName,
            accountNumber: ownerInfo.accountNumber
          }
        });
      } else {
        // Update existing owner with new tax info if provided
        await this.prisma.user.update({
            where: { id: ownerUser.id },
            data: {
                firstName: ownerInfo.name,
                personType: ownerInfo.personType,
                isTaxDeclarant: ownerInfo.isTaxDeclarant,
                regimeType: ownerInfo.regimeType,
                applyReteIva: ownerInfo.applyReteIva,
                applyReteFuente: ownerInfo.applyReteFuente,
                applyReteIca: ownerInfo.applyReteIca,
                bankName: ownerInfo.bankName,
                accountNumber: ownerInfo.accountNumber
            }
        });
      }

      // Check if relation exists
      const existingRel = await this.prisma.propertyRelation.findFirst({
        where: { propertyId: id, relationType: 'OWNER' }
      });

      if (existingRel) {
        await this.prisma.propertyRelation.update({
          where: { id: existingRel.id },
          data: { userId: ownerUser.id }
        });
      } else {
        await this.prisma.propertyRelation.create({
          data: {
            propertyId: id,
            userId: ownerUser.id,
            relationType: 'OWNER',
            startDate: new Date(),
            status: 'ACTIVE'
          }
        });
      }
    }

    return property;
  }
}
