import { PropertiesService } from './properties.service';
import { BulkImportService } from './bulk-import.service';
import { CreatePropertyDto } from './dto/create-property.dto';
import { UpdatePropertyDto } from './dto/update-property.dto';
export declare class PropertiesController {
    private readonly propertiesService;
    private readonly bulkImportService;
    constructor(propertiesService: PropertiesService, bulkImportService: BulkImportService);
    createInmueble(data: CreatePropertyDto): Promise<{
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    }>;
    createPropietario(data: any): Promise<{
        message: string;
        data: any;
    }>;
    findAll(tenantId: string): Promise<({
        assignments: ({
            agent: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            };
        } & {
            id: string;
            propertyId: string;
            agentId: string;
            assignedAt: Date;
        })[];
        relations: ({
            user: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            };
        } & {
            id: string;
            status: import("@prisma/client").$Enums.RelationStatus;
            insuranceCompany: string | null;
            relationType: import("@prisma/client").$Enums.RelationType;
            percentageOwnership: number | null;
            startDate: Date;
            endDate: Date | null;
            contractNumber: string | null;
            contractType: string | null;
            propertyId: string;
            userId: string;
        })[];
        inventoryItems: {
            comments: string | null;
            id: string;
            name: string;
            createdAt: Date;
            description: string | null;
            category: import("@prisma/client").$Enums.InventoryCategory;
            material: string | null;
            zoneId: string | null;
            propertyId: string;
            model: string | null;
            condition: import("@prisma/client").$Enums.InventoryCondition;
            brand: string | null;
            serialNumber: string | null;
            quantity: number;
            isFunctional: boolean;
            technicalDetails: import("@prisma/client/runtime/client").JsonValue | null;
            expectedLifespanMonths: number | null;
            lastInspectionDate: Date | null;
        }[];
    } & {
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    })[]>;
    findOne(id: string): Promise<({
        relations: ({
            user: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            };
        } & {
            id: string;
            status: import("@prisma/client").$Enums.RelationStatus;
            insuranceCompany: string | null;
            relationType: import("@prisma/client").$Enums.RelationType;
            percentageOwnership: number | null;
            startDate: Date;
            endDate: Date | null;
            contractNumber: string | null;
            contractType: string | null;
            propertyId: string;
            userId: string;
        })[];
    } & {
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    }) | null>;
    findByCode(tenantId: string, code: string): Promise<({
        relations: ({
            user: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            };
        } & {
            id: string;
            status: import("@prisma/client").$Enums.RelationStatus;
            insuranceCompany: string | null;
            relationType: import("@prisma/client").$Enums.RelationType;
            percentageOwnership: number | null;
            startDate: Date;
            endDate: Date | null;
            contractNumber: string | null;
            contractType: string | null;
            propertyId: string;
            userId: string;
        })[];
    } & {
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    }) | null>;
    create(data: CreatePropertyDto): Promise<{
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    }>;
    bulkImport(tenantId: string, data: any[]): Promise<{
        total: number;
        imported: number;
        skipped: number;
        errors: string[];
    }>;
    patchStatus(id: string, isActive: boolean): Promise<{
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    }>;
    update(id: string, data: UpdatePropertyDto): Promise<{
        id: string;
        status: import("@prisma/client").$Enums.PropertyStatus;
        createdAt: Date;
        isActive: boolean;
        tenantId: string;
        description: string | null;
        address: string;
        propertyType: import("@prisma/client").$Enums.PropertyType;
        title: string;
        city: string;
        department: string;
        country: string;
        latitude: number | null;
        longitude: number | null;
        areaM2: number | null;
        rooms: number | null;
        bathrooms: number | null;
        propertyCode: string | null;
        isVip: boolean;
        rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
        adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
        taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
        managementName: string | null;
        managementNit: string | null;
        insuranceCompany: string | null;
        splatUrl: string | null;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        accessToken: string | null;
        managementEmail: string | null;
        managementPhone: string | null;
        visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
        visionVideoUrl: string | null;
        parentPropertyId: string | null;
        workflowId: string | null;
    }>;
    transfer(id: string, data: {
        newOwnerId: string;
        newTenantId?: string;
        startDate: string;
    }): Promise<{
        newOwner: {
            id: string;
            status: import("@prisma/client").$Enums.RelationStatus;
            insuranceCompany: string | null;
            relationType: import("@prisma/client").$Enums.RelationType;
            percentageOwnership: number | null;
            startDate: Date;
            endDate: Date | null;
            contractNumber: string | null;
            contractType: string | null;
            propertyId: string;
            userId: string;
        };
        newTenant: {
            id: string;
            status: import("@prisma/client").$Enums.RelationStatus;
            insuranceCompany: string | null;
            relationType: import("@prisma/client").$Enums.RelationType;
            percentageOwnership: number | null;
            startDate: Date;
            endDate: Date | null;
            contractNumber: string | null;
            contractType: string | null;
            propertyId: string;
            userId: string;
        } | undefined;
    }>;
}
