import { Injectable, Logger, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { PrismaService } from '../prisma/prisma.service';
import * as bcrypt from 'bcrypt';
import * as crypto from 'crypto';
import { JwtPayload } from './jwt.strategy';

/** Hash a refresh token with SHA-256 before storing in DB (NIST SP 800-63B).
 *  The raw token is sent to the client via httpOnly cookie; only the hash lives in the DB.
 *  This way a DB breach cannot be used to replay sessions.
 */
function hashToken(token: string): string {
  return crypto.createHash('sha256').update(token).digest('hex');
}

@Injectable()
export class AuthService {
  private readonly logger = new Logger(AuthService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly jwtService: JwtService,
  ) {}

  async login(email: string, password: string) {
    // Single error message for every failure path to prevent account
    // enumeration. Distinguishing causes (user missing, user inactive,
    // sentinel password, wrong password) used to leak account state to
    // attackers iterating emails. Operationally meaningful cases are
    // logged server-side so admins can diagnose without the client
    // receiving any signal.
    const FAILURE_MESSAGE = 'Credenciales inválidas.';

    const user = await this.prisma.user.findUnique({
      where: { email },
      include: { tenant: true },
    });

    if (!user) {
      throw new UnauthorizedException(FAILURE_MESSAGE);
    }
    if (!user.isActive) {
      this.logger.warn(
        `Login attempt on inactive account: ${user.email} (id=${user.id})`,
      );
      throw new UnauthorizedException(FAILURE_MESSAGE);
    }
    if (user.passwordHash === 'vault_autogenerated') {
      this.logger.warn(
        `Login attempt on auto-generated account that never set password: ${user.email} (id=${user.id})`,
      );
      throw new UnauthorizedException(FAILURE_MESSAGE);
    }

    const isPasswordValid = await bcrypt.compare(password, user.passwordHash);
    if (!isPasswordValid) {
      throw new UnauthorizedException(FAILURE_MESSAGE);
    }

    const payload: JwtPayload = {
      sub: user.id,
      email: user.email,
      tenantId: user.tenantId,
      role: user.role,
    };

    const accessToken = this.jwtService.sign(payload);

    // Generate raw refresh token — store ONLY the SHA-256 hash in DB
    const rawRefreshToken = crypto.randomBytes(40).toString('hex');
    const tokenHash = hashToken(rawRefreshToken);

    await this.prisma.refreshToken.create({
      data: {
        userId: user.id,
        token: tokenHash, // ← stored as hash, never plaintext
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
      },
    });

    return {
      accessToken,
      refreshToken: rawRefreshToken, // ← raw token delivered to client via httpOnly cookie
      user: {
        id: user.id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.role,
        tenantId: user.tenantId,
        mustChangePassword: user.mustChangePassword,
        tenant: user.tenant
          ? { id: user.tenant.id, name: user.tenant.name }
          : null,
      },
    };
  }

  async validateToken(token: string) {
    try {
      return this.jwtService.verify(token);
    } catch {
      throw new UnauthorizedException('Token inválido o expirado.');
    }
  }

  async refreshToken(rawRefreshToken: string) {
    // Hash the incoming raw token for DB lookup — never store or search plaintext
    const tokenHash = hashToken(rawRefreshToken);

    const tokenRecord = await this.prisma.refreshToken.findUnique({
      where: { token: tokenHash },
      include: { user: { include: { tenant: true } } },
    });

    if (!tokenRecord || tokenRecord.expiresAt < new Date()) {
      if (tokenRecord) {
        await this.prisma.refreshToken.delete({
          where: { id: tokenRecord.id },
        });
      }
      throw new UnauthorizedException('Refresh token inválido o expirado');
    }

    const { user } = tokenRecord;
    if (!user.isActive) {
      throw new UnauthorizedException('Usuario inactivo');
    }

    const payload: JwtPayload = {
      sub: user.id,
      email: user.email,
      tenantId: user.tenantId,
      role: user.role,
    };
    const newAccessToken = this.jwtService.sign(payload);

    // Token rotation — delete old hash, create new hash in a single transaction
    const newRawToken = crypto.randomBytes(40).toString('hex');
    const newTokenHash = hashToken(newRawToken);

    await this.prisma.$transaction([
      this.prisma.refreshToken.delete({ where: { id: tokenRecord.id } }),
      this.prisma.refreshToken.create({
        data: {
          userId: user.id,
          token: newTokenHash,
          expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        },
      }),
    ]);

    return {
      accessToken: newAccessToken,
      refreshToken: newRawToken,
      user: {
        id: user.id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.role,
        tenantId: user.tenantId,
        mustChangePassword: user.mustChangePassword,
        tenant: user.tenant
          ? { id: user.tenant.id, name: user.tenant.name }
          : null,
      },
    };
  }
}
