import { Test, TestingModule } from '@nestjs/testing';
import { AuthService } from './auth.service';
import { JwtService } from '@nestjs/jwt';
import { UnauthorizedException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import * as bcrypt from 'bcrypt';
import * as crypto from 'crypto';

/** Minimal PrismaService mock — returns controlled data per test */
const makePrismaMock = (overrides: Record<string, unknown> = {}) => ({
  user: {
    findUnique: jest.fn(),
    findFirst: jest.fn(),
  },
  refreshToken: {
    create: jest.fn().mockResolvedValue({}),
    findUnique: jest.fn(),
    delete: jest.fn().mockResolvedValue({}),
    deleteMany: jest.fn().mockResolvedValue({ count: 0 }),
    update: jest.fn().mockResolvedValue({}),
    updateMany: jest.fn().mockResolvedValue({ count: 0 }),
  },
  $transaction: jest.fn((ops: unknown[]) => Promise.all(ops)),
  ...overrides,
});

const makeJwtMock = () => ({
  sign: jest.fn().mockReturnValue('mock.jwt.token'),
  verify: jest.fn().mockReturnValue({ sub: 'user-id' }),
});

/** Build a minimal active user object for tests */
const makeUser = (overrides: Record<string, unknown> = {}) => ({
  id: 'user-1',
  email: 'test@example.com',
  passwordHash: bcrypt.hashSync('correctPassword', 10),
  firstName: 'Test',
  lastName: 'User',
  role: 'AGENT',
  tenantId: 'tenant-1',
  isActive: true,
  mustChangePassword: false,
  tenant: { id: 'tenant-1', name: 'Test Tenant' },
  ...overrides,
});

describe('AuthService', () => {
  let service: AuthService;
  let prismaMock: ReturnType<typeof makePrismaMock>;
  let jwtMock: ReturnType<typeof makeJwtMock>;

  beforeEach(async () => {
    prismaMock = makePrismaMock();
    jwtMock = makeJwtMock();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuthService,
        { provide: PrismaService, useValue: prismaMock },
        { provide: JwtService, useValue: jwtMock },
      ],
    }).compile();

    service = module.get<AuthService>(AuthService);
  });

  // ── login() ────────────────────────────────────────────────────────────────

  describe('login()', () => {
    it('should return tokens and user on valid credentials', async () => {
      const user = makeUser();
      prismaMock.user.findUnique.mockResolvedValue(user);

      const result = await service.login('test@example.com', 'correctPassword');

      expect(result.accessToken).toBe('mock.jwt.token');
      expect(result.refreshToken).toHaveLength(80); // 40 random bytes = 80 hex chars
      expect(result.user.email).toBe('test@example.com');
    });

    it('should store a SHA-256 hash of the refresh token, not the plaintext', async () => {
      const user = makeUser();
      prismaMock.user.findUnique.mockResolvedValue(user);

      const result = await service.login('test@example.com', 'correctPassword');
      const createCall = (
        prismaMock.refreshToken.create.mock.calls as unknown[][]
      )[0][0] as {
        data: { token: string };
      };
      const storedToken = createCall.data.token;

      // The stored token must be a 64-char SHA-256 hex hash
      expect(storedToken).toHaveLength(64);
      // The stored token must NOT equal the raw token sent to the client
      expect(storedToken).not.toBe(result.refreshToken);
      // Verify the hash matches
      const expectedHash = crypto
        .createHash('sha256')
        .update(result.refreshToken)
        .digest('hex');
      expect(storedToken).toBe(expectedHash);
    });

    it('should throw UnauthorizedException for inactive user', async () => {
      prismaMock.user.findUnique.mockResolvedValue(
        makeUser({ isActive: false }),
      );
      await expect(service.login('test@example.com', 'any')).rejects.toThrow(
        UnauthorizedException,
      );
    });

    it('should throw UnauthorizedException for wrong password', async () => {
      prismaMock.user.findUnique.mockResolvedValue(makeUser());
      await expect(
        service.login('test@example.com', 'wrongPassword'),
      ).rejects.toThrow(UnauthorizedException);
    });

    it('should throw UnauthorizedException for vault_autogenerated sentinel password', async () => {
      prismaMock.user.findUnique.mockResolvedValue(
        makeUser({ passwordHash: 'vault_autogenerated' }),
      );
      await expect(service.login('test@example.com', 'any')).rejects.toThrow(
        UnauthorizedException,
      );
    });

    it('should throw UnauthorizedException for non-existent user', async () => {
      prismaMock.user.findUnique.mockResolvedValue(null);
      await expect(service.login('ghost@example.com', 'any')).rejects.toThrow(
        UnauthorizedException,
      );
    });
  });

  // ── refreshToken() ─────────────────────────────────────────────────────────

  describe('refreshToken()', () => {
    it('should return new tokens on valid refresh token', async () => {
      const rawToken = crypto.randomBytes(40).toString('hex');
      const tokenHash = crypto
        .createHash('sha256')
        .update(rawToken)
        .digest('hex');

      prismaMock.refreshToken.findUnique.mockResolvedValue({
        id: 'rt-1',
        token: tokenHash,
        expiresAt: new Date(Date.now() + 60000),
        user: makeUser(),
      });

      const result = await service.refreshToken(rawToken);
      expect(result.accessToken).toBe('mock.jwt.token');
      expect(result.refreshToken).toHaveLength(80);
    });

    it('should throw UnauthorizedException for expired refresh token', async () => {
      const rawToken = crypto.randomBytes(40).toString('hex');

      prismaMock.refreshToken.findUnique.mockResolvedValue({
        id: 'rt-1',
        token: 'any-hash',
        expiresAt: new Date(Date.now() - 1000), // already expired
        user: makeUser(),
      });

      await expect(service.refreshToken(rawToken)).rejects.toThrow(
        UnauthorizedException,
      );
    });

    it('should throw UnauthorizedException for unknown refresh token', async () => {
      prismaMock.refreshToken.findUnique.mockResolvedValue(null);
      await expect(service.refreshToken('unknown-token')).rejects.toThrow(
        UnauthorizedException,
      );
    });

    it('should rotate token — mark old as usedAt and create new in transaction', async () => {
      const rawToken = crypto.randomBytes(40).toString('hex');
      prismaMock.refreshToken.findUnique.mockResolvedValue({
        id: 'rt-1',
        token: 'hash',
        expiresAt: new Date(Date.now() + 60000),
        user: makeUser(),
      });

      await service.refreshToken(rawToken);

      // $transaction should have been called once
      expect(prismaMock.$transaction).toHaveBeenCalledTimes(1);
    });

    it('should detect reuse of an already-used refresh token and revoke all user tokens', async () => {
      const rawToken = crypto.randomBytes(40).toString('hex');
      prismaMock.refreshToken.findUnique.mockResolvedValue({
        id: 'rt-1',
        userId: 'user-1',
        token: 'hash',
        expiresAt: new Date(Date.now() + 60000),
        usedAt: new Date(Date.now() - 1000), // already rotated once
        user: makeUser(),
      });

      await expect(service.refreshToken(rawToken)).rejects.toThrow(
        UnauthorizedException,
      );
      expect(prismaMock.refreshToken.deleteMany).toHaveBeenCalledWith({
        where: { userId: 'user-1' },
      });
      // Critical: rotation must NOT happen on the reuse path
      expect(prismaMock.$transaction).not.toHaveBeenCalled();
    });

    it('should not call deleteMany on a normal (first-time) rotation', async () => {
      const rawToken = crypto.randomBytes(40).toString('hex');
      prismaMock.refreshToken.findUnique.mockResolvedValue({
        id: 'rt-1',
        userId: 'user-1',
        token: 'hash',
        expiresAt: new Date(Date.now() + 60000),
        usedAt: null,
        user: makeUser(),
      });

      await service.refreshToken(rawToken);
      expect(prismaMock.refreshToken.deleteMany).not.toHaveBeenCalled();
    });
  });

  // ── logout() ─────────────────────────────────────────────────────────────

  describe('logout()', () => {
    it('marks all of the user refresh tokens as usedAt when given a valid access token', async () => {
      jwtMock.verify.mockReturnValue({ sub: 'user-1' });

      await service.logout('mock.access.token');

      expect(prismaMock.refreshToken.updateMany).toHaveBeenCalledWith({
        where: { userId: 'user-1', usedAt: null },
        data: { usedAt: expect.any(Date) as unknown as Date },
      });
    });

    it('is a noop when called with no token', async () => {
      await service.logout(undefined);
      expect(prismaMock.refreshToken.updateMany).not.toHaveBeenCalled();
    });

    it('is a noop when access token is malformed (verify throws)', async () => {
      jwtMock.verify.mockImplementation(() => {
        throw new Error('jwt malformed');
      });
      await service.logout('garbage');
      expect(prismaMock.refreshToken.updateMany).not.toHaveBeenCalled();
    });
  });

  // ── Multi-tenant isolation ─────────────────────────────────────────────────

  describe('multi-tenant isolation', () => {
    it('should embed tenantId from DB in JWT payload, not from request', async () => {
      const user = makeUser({ tenantId: 'tenant-abc' });
      prismaMock.user.findUnique.mockResolvedValue(user);

      await service.login('test@example.com', 'correctPassword');

      const jwtPayload = (jwtMock.sign.mock.calls as unknown[][])[0][0] as {
        tenantId: string;
      };
      expect(jwtPayload.tenantId).toBe('tenant-abc');
    });
  });
});
