import { TicketsService } from './tickets.service';
import { CreateTicketDto } from './dto/create-ticket.dto';
export declare class TicketsController {
    private readonly ticketsService;
    constructor(ticketsService: TicketsService);
    create(createTicketDto: CreateTicketDto): Promise<{
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    }>;
    findAll(tenantId: string, ownerId?: string): Promise<({
        interactions: {
            id: string;
            userId: string | null;
            ticketId: string;
            channel: import("@prisma/client").$Enums.InteractionChannel;
            message: string;
            sentimentAnalysis: import("@prisma/client").$Enums.SentimentAnalysis | null;
            sentAt: Date;
        }[];
        stateLogs: ({
            state: {
                id: string;
                name: string;
                order: number;
                assignedRole: import("@prisma/client").$Enums.UserRole | null;
                slaHours: number | null;
                color: string | null;
                assignedUserId: string | null;
                workflowId: string;
            };
            completedByUser: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            } | null;
        } & {
            id: string;
            startedAt: Date;
            completedAt: Date | null;
            comment: string | null;
            ticketId: string;
            stateId: string;
            completedByUserId: string | null;
        })[];
        property: {
            id: string;
            status: import("@prisma/client").$Enums.PropertyStatus;
            createdAt: Date;
            isActive: boolean;
            tenantId: string;
            description: string | null;
            address: string;
            propertyType: import("@prisma/client").$Enums.PropertyType;
            title: string;
            city: string;
            department: string;
            country: string;
            latitude: number | null;
            longitude: number | null;
            areaM2: number | null;
            rooms: number | null;
            bathrooms: number | null;
            propertyCode: string | null;
            isVip: boolean;
            rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
            adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
            taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
            managementName: string | null;
            managementNit: string | null;
            insuranceCompany: string | null;
            splatUrl: string | null;
            attachments: import("@prisma/client/runtime/client").JsonValue | null;
            accessToken: string | null;
            managementEmail: string | null;
            managementPhone: string | null;
            visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
            visionVideoUrl: string | null;
            parentPropertyId: string | null;
            workflowId: string | null;
        };
        assignedTechnician: {
            id: string;
            createdAt: Date;
            email: string;
            passwordHash: string;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            role: import("@prisma/client").$Enums.UserRole;
            phone: string | null;
            whatsappId: string | null;
            photoUrl: string | null;
            isActive: boolean;
            additionalContacts: string | null;
            personType: string | null;
            isTaxDeclarant: boolean;
            regimeType: string | null;
            applyReteIva: boolean;
            applyReteFuente: boolean;
            applyReteIca: boolean;
            bankName: string | null;
            accountNumber: string | null;
            accountType: string | null;
            tenantId: string | null;
            roleId: string | null;
            providerId: string | null;
        } | null;
        currentState: {
            id: string;
            name: string;
            order: number;
            assignedRole: import("@prisma/client").$Enums.UserRole | null;
            slaHours: number | null;
            color: string | null;
            assignedUserId: string | null;
            workflowId: string;
        } | null;
        reportedByUser: {
            id: string;
            createdAt: Date;
            email: string;
            passwordHash: string;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            role: import("@prisma/client").$Enums.UserRole;
            phone: string | null;
            whatsappId: string | null;
            photoUrl: string | null;
            isActive: boolean;
            additionalContacts: string | null;
            personType: string | null;
            isTaxDeclarant: boolean;
            regimeType: string | null;
            applyReteIva: boolean;
            applyReteFuente: boolean;
            applyReteIca: boolean;
            bankName: string | null;
            accountNumber: string | null;
            accountType: string | null;
            tenantId: string | null;
            roleId: string | null;
            providerId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    })[]>;
    findByTechnician(id: string): Promise<({
        stateLogs: ({
            state: {
                id: string;
                name: string;
                order: number;
                assignedRole: import("@prisma/client").$Enums.UserRole | null;
                slaHours: number | null;
                color: string | null;
                assignedUserId: string | null;
                workflowId: string;
            };
            completedByUser: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            } | null;
        } & {
            id: string;
            startedAt: Date;
            completedAt: Date | null;
            comment: string | null;
            ticketId: string;
            stateId: string;
            completedByUserId: string | null;
        })[];
        property: {
            id: string;
            status: import("@prisma/client").$Enums.PropertyStatus;
            createdAt: Date;
            isActive: boolean;
            tenantId: string;
            description: string | null;
            address: string;
            propertyType: import("@prisma/client").$Enums.PropertyType;
            title: string;
            city: string;
            department: string;
            country: string;
            latitude: number | null;
            longitude: number | null;
            areaM2: number | null;
            rooms: number | null;
            bathrooms: number | null;
            propertyCode: string | null;
            isVip: boolean;
            rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
            adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
            taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
            managementName: string | null;
            managementNit: string | null;
            insuranceCompany: string | null;
            splatUrl: string | null;
            attachments: import("@prisma/client/runtime/client").JsonValue | null;
            accessToken: string | null;
            managementEmail: string | null;
            managementPhone: string | null;
            visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
            visionVideoUrl: string | null;
            parentPropertyId: string | null;
            workflowId: string | null;
        };
        currentState: {
            id: string;
            name: string;
            order: number;
            assignedRole: import("@prisma/client").$Enums.UserRole | null;
            slaHours: number | null;
            color: string | null;
            assignedUserId: string | null;
            workflowId: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    })[]>;
    findOne(id: string): Promise<({
        stateLogs: ({
            state: {
                id: string;
                name: string;
                order: number;
                assignedRole: import("@prisma/client").$Enums.UserRole | null;
                slaHours: number | null;
                color: string | null;
                assignedUserId: string | null;
                workflowId: string;
            };
            completedByUser: {
                id: string;
                createdAt: Date;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                governmentId: string | null;
                role: import("@prisma/client").$Enums.UserRole;
                phone: string | null;
                whatsappId: string | null;
                photoUrl: string | null;
                isActive: boolean;
                additionalContacts: string | null;
                personType: string | null;
                isTaxDeclarant: boolean;
                regimeType: string | null;
                applyReteIva: boolean;
                applyReteFuente: boolean;
                applyReteIca: boolean;
                bankName: string | null;
                accountNumber: string | null;
                accountType: string | null;
                tenantId: string | null;
                roleId: string | null;
                providerId: string | null;
            } | null;
        } & {
            id: string;
            startedAt: Date;
            completedAt: Date | null;
            comment: string | null;
            ticketId: string;
            stateId: string;
            completedByUserId: string | null;
        })[];
        workflow: ({
            states: {
                id: string;
                name: string;
                order: number;
                assignedRole: import("@prisma/client").$Enums.UserRole | null;
                slaHours: number | null;
                color: string | null;
                assignedUserId: string | null;
                workflowId: string;
            }[];
        } & {
            id: string;
            name: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
        }) | null;
        property: {
            id: string;
            status: import("@prisma/client").$Enums.PropertyStatus;
            createdAt: Date;
            isActive: boolean;
            tenantId: string;
            description: string | null;
            address: string;
            propertyType: import("@prisma/client").$Enums.PropertyType;
            title: string;
            city: string;
            department: string;
            country: string;
            latitude: number | null;
            longitude: number | null;
            areaM2: number | null;
            rooms: number | null;
            bathrooms: number | null;
            propertyCode: string | null;
            isVip: boolean;
            rentAmount: import("@prisma/client-runtime-utils").Decimal | null;
            adminAmount: import("@prisma/client-runtime-utils").Decimal | null;
            taxAmount: import("@prisma/client-runtime-utils").Decimal | null;
            managementName: string | null;
            managementNit: string | null;
            insuranceCompany: string | null;
            splatUrl: string | null;
            attachments: import("@prisma/client/runtime/client").JsonValue | null;
            accessToken: string | null;
            managementEmail: string | null;
            managementPhone: string | null;
            visionAnalysis: import("@prisma/client/runtime/client").JsonValue | null;
            visionVideoUrl: string | null;
            parentPropertyId: string | null;
            workflowId: string | null;
        };
        assignedTechnician: {
            id: string;
            createdAt: Date;
            email: string;
            passwordHash: string;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            role: import("@prisma/client").$Enums.UserRole;
            phone: string | null;
            whatsappId: string | null;
            photoUrl: string | null;
            isActive: boolean;
            additionalContacts: string | null;
            personType: string | null;
            isTaxDeclarant: boolean;
            regimeType: string | null;
            applyReteIva: boolean;
            applyReteFuente: boolean;
            applyReteIca: boolean;
            bankName: string | null;
            accountNumber: string | null;
            accountType: string | null;
            tenantId: string | null;
            roleId: string | null;
            providerId: string | null;
        } | null;
        currentState: {
            id: string;
            name: string;
            order: number;
            assignedRole: import("@prisma/client").$Enums.UserRole | null;
            slaHours: number | null;
            color: string | null;
            assignedUserId: string | null;
            workflowId: string;
        } | null;
        reportedByUser: {
            id: string;
            createdAt: Date;
            email: string;
            passwordHash: string;
            firstName: string;
            lastName: string;
            governmentId: string | null;
            role: import("@prisma/client").$Enums.UserRole;
            phone: string | null;
            whatsappId: string | null;
            photoUrl: string | null;
            isActive: boolean;
            additionalContacts: string | null;
            personType: string | null;
            isTaxDeclarant: boolean;
            regimeType: string | null;
            applyReteIva: boolean;
            applyReteFuente: boolean;
            applyReteIca: boolean;
            bankName: string | null;
            accountNumber: string | null;
            accountType: string | null;
            tenantId: string | null;
            roleId: string | null;
            providerId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    }) | null>;
    transition(id: string, data: {
        userId: string;
        newStateId: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    }>;
    resolve(id: string, data: {
        closureReason: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    }>;
    completeTask(id: string, data: {
        userId: string;
        comment: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    }>;
    updateSatisfaction(id: string, data: {
        stars: number;
        comment?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        tenantId: string;
        description: string;
        title: string;
        attachments: import("@prisma/client/runtime/client").JsonValue | null;
        workflowId: string | null;
        propertyId: string;
        reportedByUserPhone: string | null;
        priority: import("@prisma/client").$Enums.TicketPriority;
        severity: import("@prisma/client").$Enums.TicketSeverity;
        aiDiagnosisSummary: string | null;
        estimatedCost: import("@prisma/client-runtime-utils").Decimal | null;
        ownerApproved: boolean;
        coordinates3d: import("@prisma/client/runtime/client").JsonValue | null;
        payerResponsible: import("@prisma/client").$Enums.PayerResponsible | null;
        resolvedAt: Date | null;
        satisfactionStars: number | null;
        satisfactionComment: string | null;
        closureReason: string | null;
        reportedByUserId: string;
        currentStateId: string | null;
        assignedTechnicianId: string | null;
        assignedProviderId: string | null;
        inventoryItemId: string | null;
    }>;
}
